name: Test

on:
  workflow_dispatch: 

jobs:
  install-and-test:
    uses: Zachnjue/nodejs/.github/workflows/install.yml@main
    with:
    #   node-version: '20'
      install-command: 'npm install'
    # secrets:
    #   token: ${{ secrets.REUSABLE_WORKFLOW_TOKEN }}
