# A first workflow to play around with the editor
name: My First Worklfow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs_on: ubuntu-latest
    steps:
      - run: echo "Hello World from ${{ github.actor}}"
      - name: Checkout
        uses: actions/checkout@v4.2.2
