# A first workflow to play around with the editor
name: My First Workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  first_job:
    name: My first job
    runs-on: ubuntu-latest  # ✅ Fixed here
    steps:
      - run: echo "Hello World from ${{ github.actor }}"
      - name: Checkout
        uses: actions/checkout@v4.2.2
