name: Run with Reusable Workflow

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello World
        run: echo "Hello World"
      - name: Create a file
        run: echo "Hello World" > input.txt
      - uses: actions/upload-artifact@v4
        with:
          name: input_file
          path: input.txt

  job-2:
    needs: job-1
    uses: ./github/workflows/reusable-workflow.yml  # ✅ LOCAL REFERENCE (no @main)
    with:
      reusable_input: "job-2-input"
      filename: "input.txt"
    secrets:
      HELLO_WORLD_SECRET: ${{ secrets.HELLO_WORLD_SECRET }}

  job-3:
    needs: job-2
    runs-on: ubuntu-latest
    steps:
      - name: Print output
        run: echo "reusable_output=${{ needs.job-2.outputs.reusable_output }}"
      - uses: actions/download-artifact@v4
        with:
          name: output_file
      - name: Print file content
        run: cat input.txt
